services:
  web:
    build: 
      context: ..
      dockerfile: services/web/Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - asset-volume:/root/images
  classification:
    build:
      context: ..
      dockerfile: services/classification/Dockerfile  
    volumes:
      - asset-volume:/root/images

volumes:
  asset-volume:

