services:
  # web:
  #   build: 
  #     context: ..
  #     dockerfile: services/web/Dockerfile
  #   ports:
  #     - "8000:5000"
  #   volumes:
  #     - asset-volume:/root/images
  classification:
    build:
      context: ..
      dockerfile: services/classification/Dockerfile 
    environment:
      IMG: ${IMG}
      IMG_PATH: ${IMG_PATH} 
    volumes:
      # - asset-volume:/root/images
      - classification-config:${IMG_PATH}

volumes:
  # asset-volume:
  classification-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${IMGS_ROOT}"
