services:
  classification:
    build:
      context: ..
      dockerfile: services/classification/Dockerfile 
    environment:
      IMG: ${IMG}
      IMG_PATH: ${IMG_PATH} 
    volumes:
      - classification-config:${IMG_PATH}

volumes:
  classification-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "${IMGS_ROOT}"
